name: Build Windows

on:
  push:
    branches:
      - Krypton
  pull_request:
    branches:
      - Krypton
  workflow_dispatch:

jobs:
  build-kodi:
    name: Build Kodi (Windows)
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Add CMake and MSYS2 to PATH
        shell: cmd
        run: |
          echo C:\msys64\usr\bin>>%GITHUB_PATH%
          echo C:\msys64\bin>>%GITHUB_PATH%

      - name: Update MSYS2 package database
        shell: cmd
        run: bash -lc "pacman --needed --noconfirm -Sy"

      - name: Link MSYS2 into BuildDependencies
        shell: cmd
        run: mklink /j %GITHUB_WORKSPACE%\project\BuildDependencies\msys64 C:\msys64

      - name: Download build dependencies
        shell: cmd
        working-directory: project/BuildDependencies
        run: DownloadBuildDeps.bat

      - name: Download and prepare precompiled MinGW libraries
        shell: pwsh
        working-directory: project/BuildDependencies
        run: |
          bash -c "wget -O - http://repo.msys2.org/mingw/i686/mingw-w64-i686-ffmpeg-3.1.1-1-any.pkg.tar.xz | tar xJv"
          bash -c "wget -O - http://repo.msys2.org/mingw/i686/mingw-w64-i686-libdvdcss-1.4.0-1-any.pkg.tar.xz | tar xJv"
          bash -c "wget -O - http://repo.msys2.org/mingw/i686/mingw-w64-i686-libdvdnav-5.0.3-1-any.pkg.tar.xz | tar xJv"
          bash -c "wget -O - http://repo.msys2.org/mingw/i686/mingw-w64-i686-libdvdread-5.0.3-1-any.pkg.tar.xz | tar xJv"
          # Rename lib*.dll.a -> *.lib so MSVC can find them
          Get-ChildItem mingw32\lib\lib*.dll.a | ForEach-Object {
            $newName = $_.Name.SubString(3) -replace "\.dll\.a$", ".lib"
            Rename-Item $_.FullName (Join-Path $_.DirectoryName $newName)
          }
          xcopy /s /y mingw32\*.* .
          xcopy /s /y mingw32\bin\*.dll $env:GITHUB_WORKSPACE\system\

      - name: Configure with CMake
        shell: cmd
        run: |
          mkdir kodi-build
          cd kodi-build
          cmake -G "Visual Studio 16 2019" -A Win32 ..\project\cmake

      - name: Build
        shell: cmd
        working-directory: kodi-build
        run: cmake --build . --target ALL_BUILD --config RelWithDebInfo
